<?php

use App\Http\Controllers\AjaxController;
use App\Models\User;
use GuzzleHttp\Psr7\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Route;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/
// Methode ajax
Route::post('/check_email', [AjaxController::class , 'check_email'])->name('check_email');
Route::post('/check_matricule', [AjaxController::class , 'check_matricule'])->name('check_matricule');
Route::post('/check_poste', [AjaxController::class , 'check_poste'])->name('check_poste');
Route::post('/check_position_utilisateur_poste', [AjaxController::class , 'check_position_utilisateur_poste'])->name('check_position_utilisateur_poste');
Route::post('/control', [AjaxController::class , 'control'])->name('control');
Route::post('/check_horaire_poste', [AjaxController::class , 'check_horaire_poste'])->name('check_horaire_poste');
Route::get('/control', [AjaxController::class , 'control'])->name('control');
Route::get('/export-prestations-pdf', [AjaxController::class, 'exportPdf'])->name('export.prestations.pdf');
Route::get('/check_remboursement', [AjaxController::class , 'check_remboursement'])->name('check_remboursement');
Route::get('/check_remboursement_1', [AjaxController::class , 'check_remboursement_1'])->name('check_remboursement_1');
Route::post('/check_groupe', [AjaxController::class , 'check_groupe'])->name('check_groupe');
Route::post('/add_listespaies', [AjaxController::class , 'add_listespaies'])->name('add_listespaies');
Route::post('/add_listesfactures', [AjaxController::class , 'add_listesfactures'])->name('add_listesfactures');
Route::post('/check_contrevenant', [AjaxController::class , 'check_contrevenant'])->name('check_contrevenant');
Route::post('/check_verbalisateur', [AjaxController::class , 'check_verbalisateur'])->name('check_verbalisateur');
Route::post('/check_type_frais', [AjaxController::class , 'check_type_frais'])->name('check_type_frais');
Route::post('/check_type_documents', [AjaxController::class , 'check_type_documents'])->name('check_type_documents');
Route::post('/check_point_vente', [AjaxController::class , 'check_point_vente'])->name('check_point_vente');
Route::post('/check_stock', [AjaxController::class , 'check_stock'])->name('check_stock');
Route::post('/check_tables', [AjaxController::class , 'check_tables'])->name('check_tables');
Route::post('/check_societe', [AjaxController::class , 'check_societe'])->name('check_societe');
Route::get('/check_solde', [AjaxController::class , 'check_solde'])->name('check_solde');
Route::get('/check_solde_1', [AjaxController::class , 'check_solde_1'])->name('check_solde_1');
Route::get('/check_solde_2', [AjaxController::class , 'check_solde_2'])->name('check_solde_2');
Route::get('/print_facture', [AjaxController::class , 'print_facture'])->name('print_facture');
Route::get('/get_credit', [AjaxController::class , 'get_credit'])->name('get_credit');
Route::get('/get_image_utilisateur', [AjaxController::class , 'get_image_utilisateur'])->name('get_image_utilisateur');
Route::get('/get_credit_2', [AjaxController::class , 'get_credit_2'])->name('get_credit_2');
Route::get('/check_seuil_maximum', [AjaxController::class , 'check_seuil_maximum'])->name('check_seuil_maximum');
Route::get('/check_seuil_minimum', [AjaxController::class , 'check_seuil_minimum'])->name('check_seuil_minimum');
Route::get('/check_solde_sortie', [AjaxController::class , 'check_solde_sortie'])->name('check_solde_sortie');
Route::get('/check_solde_encours', [AjaxController::class , 'check_solde_encours'])->name('check_solde_encours');
Route::get('/check_solde_encours_1', [AjaxController::class , 'check_solde_encours_1'])->name('check_solde_encours_1');
Route::get('/check_solde_encours_2', [AjaxController::class , 'check_solde_encours_2'])->name('check_solde_encours_2');
Route::post('/check_type_infractions', [AjaxController::class , 'check_type_infractions'])->name('check_type_infractions');
Route::post('/check_code_comptable', [AjaxController::class , 'check_code_comptable'])->name('check_code_comptable');
Route::post('/check_groupe_1', [AjaxController::class , 'check_groupe_1'])->name('check_groupe_1');
Route::post('/check_contrevenant_1', [AjaxController::class , 'check_contrevenant_1'])->name('check_contrevenant_1');
Route::post('/check_verbalisateur_1', [AjaxController::class , 'check_verbalisateur_1'])->name('check_verbalisateur_1');
Route::post('/check_type_frais_1', [AjaxController::class , 'check_type_frais_1'])->name('check_type_frais_1');
Route::post('/check_type_documents_1', [AjaxController::class , 'check_type_documents_1'])->name('check_type_documents_1');
Route::post('/check_point_ventes_1', [AjaxController::class , 'check_point_ventes_1'])->name('check_point_ventes_1');
Route::post('/check_stocks_1', [AjaxController::class , 'check_stocks_1'])->name('check_stocks_1');
Route::post('/check_tables_1', [AjaxController::class , 'check_tables_1'])->name('check_tables_1');
Route::post('/check_societe_1', [AjaxController::class , 'check_societe_1'])->name('check_societe_1');
Route::post('/check_type_infractions_1', [AjaxController::class , 'check_type_infractions_1'])->name('check_type_infractions_1');
Route::post('/add_groupe', [AjaxController::class , 'add_groupe'])->name('add_groupe');
Route::post('/add_contrevenant', [AjaxController::class , 'add_contrevenant'])->name('add_contrevenant');
Route::post('/add_verbalisateur', [AjaxController::class , 'add_verbalisateur'])->name('add_verbalisateur');
Route::post('/add_type_frais', [AjaxController::class , 'add_type_frais'])->name('add_type_frais');
Route::post('/add_type_documents', [AjaxController::class , 'add_type_documents'])->name('add_type_documents');
Route::post('/add_point_vente', [AjaxController::class , 'add_point_vente'])->name('add_point_vente');
Route::post('/add_stock', [AjaxController::class , 'add_stock'])->name('add_stock');
Route::post('/add_table', [AjaxController::class , 'add_table'])->name('add_table');
Route::post('/add_societe', [AjaxController::class , 'add_societe'])->name('add_societe');
Route::post('/add_activiter', [AjaxController::class , 'add_activiter'])->name('add_activiter');
Route::post('/edit_activiter', [AjaxController::class , 'edit_activiter'])->name('edit_activiter');
Route::post('/add_app_article', [AjaxController::class , 'add_app_article'])->name('add_app_article');
Route::post('/add_achat_article', [AjaxController::class , 'add_achat_article'])->name('add_achat_article');
Route::post('/add_solde', [AjaxController::class , 'add_solde'])->name('add_solde');
Route::post('/add_type_infractions', [AjaxController::class , 'add_type_infractions'])->name('add_type_infractions');
Route::post('/add_invitations', [AjaxController::class , 'add_invitations'])->name('add_invitations');
Route::post('/add_contentieux', [AjaxController::class , 'add_contentieux'])->name('add_contentieux');
Route::post('/add_decisions', [AjaxController::class , 'add_decisions'])->name('add_decisions');
Route::post('/confirm_presence', [AjaxController::class , 'confirm_presence'])->name('confirm_presence');
Route::post('/envoyer_alerte', [AjaxController::class , 'envoyer_alerte'])->name('envoyer_alerte');
Route::post('/add_documents', [AjaxController::class , 'add_documents'])->name('add_documents');
Route::post('/add_sortie', [AjaxController::class , 'add_sortie'])->name('add_sortie');
Route::post('/add_article', [AjaxController::class , 'add_article'])->name('add_article');
Route::post('/add_entre', [AjaxController::class , 'add_entre'])->name('add_entre');
Route::post('/add_depense', [AjaxController::class , 'add_depense'])->name('add_depense');
Route::get('/get_entre', [AjaxController::class , 'get_entre'])->name('get_entre');
Route::get('/get_prix_article', [AjaxController::class , 'get_prix_article'])->name('get_prix_article');
Route::get('/get_devise_article', [AjaxController::class , 'get_devise_article'])->name('get_devise_article');
Route::get('/get_approvisionnement', [AjaxController::class , 'get_approvisionnement'])->name('get_approvisionnement');
Route::get('/get_achat', [AjaxController::class , 'get_achat'])->name('get_achat');
Route::get('/get_sortie', [AjaxController::class , 'get_sortie'])->name('get_sortie');
Route::get('/solde_actif', [AjaxController::class , 'solde_actif'])->name('solde_actif');
Route::post('/add_frais_contentieux', [AjaxController::class , 'add_frais_contentieux'])->name('add_frais_contentieux');
Route::post('/add_frais_contentieux_', [AjaxController::class , 'add_frais_contentieux_'])->name('add_frais_contentieux_');
Route::post('/check_user', [AjaxController::class , 'check_user'])->name('check_user');
Route::post('/check_user_in_listespaies', [AjaxController::class , 'check_user_in_listespaies'])->name('check_user_in_listespaies');
Route::post('/add_user_in_listespaies', [AjaxController::class , 'add_user_in_listespaies'])->name('add_user_in_listespaies');
Route::post('/add_client_in_listesfactures', [AjaxController::class , 'add_client_in_listesfactures'])->name('add_client_in_listesfactures');
Route::post('/check_client_in_listesfactures', [AjaxController::class , 'check_client_in_listesfactures'])->name('check_client_in_listesfactures');
Route::get('/refresh_approuver_frais', [AjaxController::class , 'refresh_approuver_frais'])->name('refresh_approuver_frais');
Route::get('/refresh_reprise_article', [AjaxController::class , 'refresh_reprise_article'])->name('refresh_reprise_article');
Route::get('/get_refresh_paiementsfactures', [AjaxController::class , 'get_refresh_paiementsfactures'])->name('get_refresh_paiementsfactures');
Route::get('/get_refresh_programme', [AjaxController::class , 'get_refresh_programme'])->name('get_refresh_programme');
Route::get('/check_user_in_listespaies', [AjaxController::class , 'check_user_in_listespaies'])->name('check_user_in_listespaies');
Route::post('/edit_groupe', [AjaxController::class , 'edit_groupe'])->name('edit_groupe');
Route::post('/edit_article', [AjaxController::class , 'edit_article'])->name('edit_article');
Route::post('/edit_contrevenant', [AjaxController::class , 'edit_contrevenant'])->name('edit_contrevenant');
Route::post('/edit_verbalisateur', [AjaxController::class , 'edit_verbalisateur'])->name('edit_verbalisateur');
Route::post('/edit_type_frais', [AjaxController::class , 'edit_type_frais'])->name('edit_type_frais');
Route::post('/edit_type_documents', [AjaxController::class , 'edit_type_documents'])->name('edit_type_documents');
Route::post('/edit_point_ventes', [AjaxController::class , 'edit_point_ventes'])->name('edit_point_ventes');
Route::post('/edit_stocks', [AjaxController::class , 'edit_stocks'])->name('edit_stocks');
Route::post('/edit_tables', [AjaxController::class , 'edit_tables'])->name('edit_tables');
Route::post('/edit_societe', [AjaxController::class , 'edit_societe'])->name('edit_societe');
Route::post('/edit_type_infractions', [AjaxController::class , 'edit_type_infractions'])->name('edit_type_infractions');
Route::post('/edit_type_infractions', [AjaxController::class , 'edit_type_infractions'])->name('edit_type_infractions');
Route::post('/upload_profil', [AjaxController::class, 'upload_profil'])->name('upload_profil');
Route::post('/upload_profil_add', [AjaxController::class, 'upload_profil_add'])->name('upload_profil_add');
Route::post('/upload_logo_add', [AjaxController::class, 'upload_logo_add'])->name('upload_logo_add');
Route::post('/upload_profil_edit', [AjaxController::class, 'upload_profil_edit'])->name('upload_profil_edit');
Route::post('/upload_logo_edit', [AjaxController::class, 'upload_logo_edit'])->name('upload_logo_edit');
Route::get('/refresh_editinvitations', [AjaxController::class , 'refresh_editinvitations'])->name('refresh_editinvitations');
Route::get('/refresh_editdecisions', [AjaxController::class , 'refresh_editdecisions'])->name('refresh_editdecisions');
Route::get('/refresh_detaildecisions', [AjaxController::class , 'refresh_detaildecisions'])->name('refresh_detaildecisions');
Route::get('/refresh_detailfactures', [AjaxController::class , 'refresh_detailfactures'])->name('refresh_detailfactures');
Route::get('/refresh_detailcredits', [AjaxController::class , 'refresh_detailcredits'])->name('refresh_detailcredits');
Route::get('/refresh_detailpaies', [AjaxController::class , 'refresh_detailpaies'])->name('refresh_detailpaies');
Route::get('/refresh_detail_listes_factures', [AjaxController::class , 'refresh_detail_listes_factures'])->name('refresh_detail_listes_factures');
Route::get('/refresh_programme', [AjaxController::class , 'refresh_programme'])->name('refresh_detail_listes_factures');
Route::get('/refresh_detailcredits_2', [AjaxController::class , 'refresh_detailcredits_2'])->name('refresh_detailcredits_2');
Route::get('/refresh_detailcredits_3', [AjaxController::class , 'refresh_detailcredits_3'])->name('refresh_detailcredits_3');
Route::get('/refresh_detailcredits_4', [AjaxController::class , 'refresh_detailcredits_4'])->name('refresh_detailcredits_4');
Route::get('/refresh_detailfactureas', [AjaxController::class , 'refresh_detailfactureas'])->name('refresh_detailfactureas');
Route::get('/refresh_detailfactureass', [AjaxController::class , 'refresh_detailfactureass'])->name('refresh_detailfactureass');
Route::get('/refresh_detailfacturess', [AjaxController::class , 'refresh_detailfacturess'])->name('refresh_detailfacturess');
Route::get('/rapp', [AjaxController::class , 'rapp'])->name('rapp');
Route::get('/bilan_1', [AjaxController::class , 'bilan_1'])->name('bilan_1');
Route::get('/bilan_2', [AjaxController::class , 'bilan_2'])->name('bilan_2');
Route::get('/bilan_3', [AjaxController::class , 'bilan_3'])->name('bilan_3');
Route::post('/check_email_utilisateur', [AjaxController::class , 'check_email_utilisateur'])->name('check_email_utilisateur');
Route::post('/add_rendez_vous', [AjaxController::class , 'add_rendez_vous'])->name('add_rendez_vous');
Route::post('/check_email_utilisateur_1', [AjaxController::class , 'check_email_utilisateur_1'])->name('check_email_utilisateur_1');
Route::post('/check_phone_utilisateur', [AjaxController::class , 'check_phone_utilisateur'])->name('check_phone_utilisateur');
Route::post('/check_phone_utilisateur_1', [AjaxController::class , 'check_phone_utilisateur_1'])->name('check_phone_utilisateur_1');
Route::post('/check_poste_existe', [AjaxController::class , 'check_poste_existe'])->name('check_poste_existe');
Route::post('/check_ecole_existe', [AjaxController::class , 'check_ecole_existe'])->name('check_ecole_existe');
Route::post('/check_eleve_existe', [AjaxController::class , 'check_eleve_existe'])->name('check_eleve_existe');
Route::post('/check_eleve_existe_1', [AjaxController::class , 'check_eleve_existe_1'])->name('check_eleve_existe_1');
Route::post('/check_poste_existe_1', [AjaxController::class , 'check_poste_existe_1'])->name('check_poste_existe_1');
Route::post('/check_ecole_existe_1', [AjaxController::class , 'check_ecole_existe_1'])->name('check_ecole_existe_1');
Route::post('/check_mdpa', [AjaxController::class , 'check_mdpa'])->name('check_mdpa');
Route::post('/add_utilisateur', [AjaxController::class , 'add_utilisateur'])->name('add_utilisateur');
Route::post('/add_prestation', [AjaxController::class , 'add_prestation'])->name('add_prestation');
Route::post('/add_poste', [AjaxController::class , 'add_poste'])->name('add_poste');
Route::post('/add_ecole', [AjaxController::class , 'add_ecole'])->name('add_ecole');
Route::post('/add_eleve', [AjaxController::class , 'add_eleve'])->name('add_eleve');
Route::post('/edit_poste', [AjaxController::class , 'edit_poste'])->name('edit_poste');
Route::post('/edit_ecole', [AjaxController::class , 'edit_ecole'])->name('edit_ecole');
Route::post('/edit_eleve', [AjaxController::class , 'edit_eleve'])->name('edit_eleve');
Route::post('/add_client', [AjaxController::class , 'add_client'])->name('add_client');
Route::post('/add_credit', [AjaxController::class , 'add_credit'])->name('add_credit');
Route::post('/edit_utilisateur', [AjaxController::class , 'edit_utilisateur'])->name('edit_utilisateur');
Route::post('/edit_utilisateur_profil', [AjaxController::class , 'edit_utilisateur_profil'])->name('edit_utilisateur_profil');
Route::post('/edit_client', [AjaxController::class , 'edit_client'])->name('edit_client');
Route::post('/edit_invitations', [AjaxController::class , 'edit_invitations'])->name('edit_invitations');
Route::post('/edit_decisions', [AjaxController::class , 'edit_decisions'])->name('edit_decisions');
Route::get('/refresh_editutilisateur', [AjaxController::class , 'refresh_editutilisateur'])->name('refresh_editutilisateur');
Route::get('/refresh_editactivite', [AjaxController::class , 'refresh_editactivite'])->name('refresh_editactivite');
Route::get('/refresh_editposte', [AjaxController::class , 'refresh_editposte'])->name('refresh_editposte');
Route::get('/refresh_editecole', [AjaxController::class , 'refresh_editecole'])->name('refresh_editecole');
Route::get('/refresh_editeleve', [AjaxController::class , 'refresh_editeleve'])->name('refresh_editeleve');
Route::get('/refresh_editclient', [AjaxController::class , 'refresh_editclient'])->name('refresh_editclient');
Route::get('/refresh_editarticle', [AjaxController::class , 'refresh_editarticle'])->name('refresh_editarticle');
Route::get('/refresh_appro', [AjaxController::class , 'refresh_appro'])->name('refresh_appro');
Route::get('/get_liste_credit', [AjaxController::class , 'get_liste_credit'])->name('get_liste_credit');
Route::get('/get_liste_employe', [AjaxController::class , 'get_liste_employe'])->name('get_liste_employe');
Route::get('/get_liste_qr_code', [AjaxController::class , 'get_liste_qr_code'])->name('get_liste_qr_code');
Route::get('/get_one_qr_code', [AjaxController::class , 'get_one_qr_code'])->name('get_one_qr_code');
Route::get('/get_liste_client', [AjaxController::class , 'get_liste_client'])->name('get_liste_client');
Route::get('/get_print_paie', [AjaxController::class , 'get_print_paie'])->name('get_print_paie');
Route::get('/get_print_listes_factures', [AjaxController::class , 'get_print_listes_factures'])->name('get_print_listes_factures');
Route::get('/send_factures_e', [AjaxController::class , 'send_factures_e'])->name('send_factures_e');
Route::get('/send_factures_w', [AjaxController::class , 'send_factures_w'])->name('send_factures_w');
Route::get('/refresh_deleteutilisateur', [AjaxController::class , 'refresh_deleteutilisateur'])->name('refresh_deleteutilisateur');
Route::get('/refresh_deleteposte', [AjaxController::class , 'refresh_deleteposte'])->name('refresh_deleteposte');
Route::get('/refresh_deleteecole', [AjaxController::class , 'refresh_deleteecole'])->name('refresh_deleteecole');
Route::get('/refresh_deleteeleve', [AjaxController::class , 'refresh_deleteeleve'])->name('refresh_deleteeleve');
Route::get('/refresh_deleteclient', [AjaxController::class , 'refresh_deleteclient'])->name('refresh_deleteclient');
Route::get('/delete_operation', [AjaxController::class , 'delete_operation'])->name('delete_operation');
Route::get('/delete_operation_2', [AjaxController::class , 'delete_operation_2'])->name('delete_operation_2');
Route::get('/refresh_deletearticle', [AjaxController::class , 'refresh_deletearticle'])->name('refresh_deletearticle');
Route::get('/refresh_deletegroupe', [AjaxController::class , 'refresh_deletegroupe'])->name('refresh_deletegroupe');
Route::get('/refresh_deletecontrevenant', [AjaxController::class , 'refresh_deletecontrevenant'])->name('refresh_deletecontrevenant');
Route::get('/refresh_deleteverbalisateur', [AjaxController::class , 'refresh_deleteverbalisateur'])->name('refresh_deleteverbalisateur');
Route::get('/refresh_deleteinvitation', [AjaxController::class , 'refresh_deleteinvitation'])->name('refresh_deleteinvitation');
Route::get('/refresh_deletedecision', [AjaxController::class , 'refresh_deletedecision'])->name('refresh_deletedecision');
Route::get('/refresh_delete_type_frais', [AjaxController::class , 'refresh_delete_type_frais'])->name('refresh_delete_type_frais');
Route::get('/refresh_delete_type_documents', [AjaxController::class , 'refresh_delete_type_documents'])->name('refresh_delete_type_documents');
Route::get('/refresh_delete_point_ventes', [AjaxController::class , 'refresh_delete_point_ventes'])->name('refresh_delete_point_ventes');
Route::get('/refresh_delete_stocks', [AjaxController::class , 'refresh_delete_stocks'])->name('refresh_delete_stocks');
Route::get('/refresh_delete_tables', [AjaxController::class , 'refresh_delete_tables'])->name('refresh_delete_tables');
Route::get('/refresh_delete_fichier_documents', [AjaxController::class , 'refresh_delete_fichier_documents'])->name('refresh_delete_fichier_documents');
Route::get('/refresh_delete_societe', [AjaxController::class , 'refresh_delete_societe'])->name('refresh_delete_societe');
Route::get('/refresh_delete_paie', [AjaxController::class , 'refresh_delete_paie'])->name('refresh_delete_paie');
Route::get('/refresh_delete_listesfactures', [AjaxController::class , 'refresh_delete_listesfactures'])->name('refresh_delete_listesfactures');
Route::get('/refresh_delete_rendez_vous', [AjaxController::class , 'refresh_delete_rendez_vous'])->name('refresh_delete_rendez_vous');
Route::get('/refresh_delete_solde', [AjaxController::class , 'refresh_delete_solde'])->name('refresh_delete_solde');
Route::get('/refresh_delete_activites', [AjaxController::class , 'refresh_delete_activites'])->name('refresh_delete_activites');
Route::get('/refresh_activer_solde', [AjaxController::class , 'refresh_activer_solde'])->name('refresh_activer_solde');
Route::get('/refresh_activer_paie', [AjaxController::class , 'refresh_activer_paie'])->name('refresh_activer_paie');
Route::get('/refresh_activer_listesfactures', [AjaxController::class , 'refresh_activer_listesfactures'])->name('refresh_activer_listesfactures');
Route::get('/refresh_desactiver_alerte_centrale', [AjaxController::class , 'refresh_desactiver_alerte_centrale'])->name('refresh_desactiver_alerte_centrale');
Route::get('/refresh_desactiver_alerte_centrale_1', [AjaxController::class , 'refresh_desactiver_alerte_centrale_1'])->name('refresh_desactiver_alerte_centrale_1');
Route::get('/refresh_alerte_centrale', [AjaxController::class , 'refresh_alerte_centrale'])->name('refresh_alerte_centrale');
Route::get('/refresh_alerte_centrale_1', [AjaxController::class , 'refresh_alerte_centrale_1'])->name('refresh_alerte_centrale_1');
Route::get('/refresh_transfert_alerte_centrale', [AjaxController::class , 'refresh_transfert_alerte_centrale'])->name('refresh_transfert_alerte_centrale');
Route::get('/refresh_transfert_alerte_centrale_1', [AjaxController::class , 'refresh_transfert_alerte_centrale_1'])->name('refresh_transfert_alerte_centrale_1');
Route::get('/count_alerte_etat_1', [AjaxController::class , 'count_alerte_etat_1'])->name('count_alerte_etat_1');
Route::get('/count_alerte_etat_2', [AjaxController::class , 'count_alerte_etat_2'])->name('count_alerte_etat_2');
Route::get('/refresh_activer_poste', [AjaxController::class , 'refresh_activer_poste'])->name('refresh_activer_poste');
Route::get('/refresh_activer_rendez_vous', [AjaxController::class , 'refresh_activer_rendez_vous'])->name('refresh_activer_rendez_vous');
Route::get('/refresh_cloturer_solde', [AjaxController::class , 'refresh_cloturer_solde'])->name('refresh_cloturer_solde');
Route::get('/refresh_cloturer_paie', [AjaxController::class , 'refresh_cloturer_paie'])->name('refresh_cloturer_paie');
Route::get('/refresh_cloturer_listesfactures', [AjaxController::class , 'refresh_cloturer_listesfactures'])->name('refresh_cloturer_listesfactures');
Route::get('/refresh_cloturer_poste', [AjaxController::class , 'refresh_cloturer_poste'])->name('refresh_cloturer_poste');
Route::get('/refresh_cloturer_rendez_vous', [AjaxController::class , 'refresh_cloturer_rendez_vous'])->name('refresh_cloturer_rendez_vous');
Route::get('/refresh_delete_type_infractions', [AjaxController::class , 'refresh_delete_type_infractions'])->name('refresh_delete_type_infractions');
Route::get('/refresh_editgroupe', [AjaxController::class , 'refresh_editgroupe'])->name('refresh_editgroupe');
Route::get('/cloturer_proces', [AjaxController::class , 'cloturer_proces'])->name('cloturer_proces');
Route::get('/refresh_editcontrevenant', [AjaxController::class , 'refresh_editcontrevenant'])->name('refresh_editcontrevenant');
Route::get('/refresh_editcontentieux', [AjaxController::class , 'refresh_editcontentieux'])->name('refresh_editcontentieux');
Route::get('/refresh_editcontentieux_2', [AjaxController::class , 'refresh_editcontentieux_2'])->name('refresh_editcontentieux_2');
Route::get('/refresh_editcontentieux_3', [AjaxController::class , 'refresh_editcontentieux_3'])->name('refresh_editcontentieux_3');
Route::get('/refresh_editverbalisateur', [AjaxController::class , 'refresh_editverbalisateur'])->name('refresh_editverbalisateur');
Route::get('/refresh_edit_type_frais', [AjaxController::class , 'refresh_edit_type_frais'])->name('refresh_edit_type_frais');
Route::get('/refresh_edit_type_documents', [AjaxController::class , 'refresh_edit_type_documents'])->name('refresh_edit_type_documents');
Route::get('/refresh_edit_stocks', [AjaxController::class , 'refresh_edit_stocks'])->name('refresh_edit_stocks');
Route::get('/refresh_edit_point_ventes', [AjaxController::class , 'refresh_edit_point_ventes'])->name('refresh_edit_point_ventes');
Route::get('/refresh_edit_tables', [AjaxController::class , 'refresh_edit_tables'])->name('refresh_edit_tables');
Route::get('/refresh_table_point_ventes', [AjaxController::class , 'refresh_table_point_ventes'])->name('refresh_table_point_ventes');
Route::get('/refresh_edit_societe', [AjaxController::class , 'refresh_edit_societe'])->name('refresh_edit_societe');
Route::get('/refresh_edit_type_infractions', [AjaxController::class , 'refresh_edit_type_infractions'])->name('refresh_edit_type_infractions');
Route::get('/refresh_write', [AjaxController::class , 'refresh_write'])->name('refresh_write');
Route::get('/refresh_affectation_stock_vente', [AjaxController::class , 'refresh_affectation_stock_vente'])->name('refresh_affectation_stock_vente');
Route::get('/refresh_affectation_table_utilisateur', [AjaxController::class , 'refresh_affectation_table_utilisateur'])->name('refresh_affectation_table_utilisateur');
Route::get('/refresh_article_stock', [AjaxController::class , 'refresh_article_stock'])->name('refresh_article_stock');
Route::get('/etat_display', [AjaxController::class , 'etat_display'])->name('etat_display');
Route::get('/etat_affectation_pointdeventes', [AjaxController::class , 'etat_affectation_pointdeventes'])->name('etat_affectation_pointdeventes');
Route::get('/etat_affectation_table_utilisateur', [AjaxController::class , 'etat_affectation_table_utilisateur'])->name('etat_affectation_table_utilisateur');
Route::get('/etat_add', [AjaxController::class , 'etat_add'])->name('etat_add');
Route::get('/etat_edit', [AjaxController::class , 'etat_edit'])->name('etat_edit');
Route::get('/etat_delete', [AjaxController::class , 'etat_delete'])->name('etat_delete');
Route::get('/get_client_by_activite', [AjaxController::class , 'get_client_by_activite'])->name('get_client_by_activite');
Route::post('/check_mdp', [AjaxController::class , 'check_mdp'])->name('check_mdp');
Route::get('/check_nom_article', [AjaxController::class , 'check_nom_article'])->name('check_nom_article');
Route::get('/check_nom_activiter', [AjaxController::class , 'check_nom_activiter'])->name('check_nom_activiter');
Route::get('/check_edit_nom_activiter', [AjaxController::class , 'check_edit_nom_activiter'])->name('check_edit_nom_activiter');
Route::get('/check_nom_article_1', [AjaxController::class , 'check_nom_article_1'])->name('check_nom_article_1');
Route::post('/deconnexion', [AjaxController::class , 'deconnexion'])->name('deconnexion');
Route::post('/upload', [AjaxController::class , 'upload'])->name('upload');
Route::post('/upload_fichier_sortie', [AjaxController::class , 'upload_fichier_sortie'])->name('upload_fichier_sortie');
Route::post('/upload_2', [AjaxController::class , 'upload_2'])->name('upload_2');
Route::get('/get_detail_p', [AjaxController::class , 'get_detail_p'])->name('get_detail_p');
Route::get('/get_detail_p_1', [AjaxController::class , 'get_detail_p_1'])->name('get_detail_p_1');
Route::get('/get_detail_p_2', [AjaxController::class , 'get_detail_p_2'])->name('get_detail_p_2');
Route::get('/save_p', [AjaxController::class , 'save_p'])->name('save_p');
Route::get('/save_p_1', [AjaxController::class , 'save_p_1'])->name('save_p_1');
Route::get('/save_p_2', [AjaxController::class , 'save_p_2'])->name('save_p_2');
Route::get('/get_contentieux', [AjaxController::class , 'get_contentieux'])->name('get_contentieux');
Route::get('/get_mois', [AjaxController::class , 'get_mois'])->name('get_mois');
Route::get('/get_mois_1', [AjaxController::class , 'get_mois_1'])->name('get_mois_1');
Route::get('/get_mois_2', [AjaxController::class , 'get_mois_2'])->name('get_mois_2');
Route::get('/get_user_where_not_in_listespaies', [AjaxController::class , 'get_user_where_not_in_listespaies'])->name('get_user_where_not_in_listespaies');
Route::get('/get_user_where_not_in_listesfactures', [AjaxController::class , 'get_user_where_not_in_listesfactures'])->name('get_user_where_not_in_listesfactures');
Route::get('/get_mois_where_not_in_prestation', [AjaxController::class , 'get_mois_where_not_in_prestation'])->name('get_mois_where_not_in_prestation');
Route::get('/get_detail_programme', [AjaxController::class , 'get_detail_programme'])->name('get_detail_programme');
Route::get('/get_numero_facture', [AjaxController::class , 'get_numero_facture'])->name('get_numero_facture');
Route::get('/get_numero_facture_1', [AjaxController::class , 'get_numero_facture_1'])->name('get_numero_facture_1');
Route::get('/get_delete_fichier', [AjaxController::class , 'get_delete_fichier'])->name('get_delete_fichier');
Route::get('/get_numero_facture_a', [AjaxController::class , 'get_numero_facture_a'])->name('get_numero_facture_a');
Route::get('/get_numero_facture_b', [AjaxController::class , 'get_numero_facture_b'])->name('get_numero_facture_b');
Route::get('/get_solde_initial', [AjaxController::class , 'get_solde_initial'])->name('get_solde_initial');
Route::get('/refresh_partager_fichier', [AjaxController::class , 'refresh_partager_fichier'])->name('refresh_partager_fichier');
Route::get('/permission_fichier', [AjaxController::class , 'permission_fichier'])->name('permission_fichier');
Route::get('/check_paie_facture', [AjaxController::class , 'check_paie_facture'])->name('check_paie_facture');
Route::get('/get_all_facture', [AjaxController::class , 'get_all_facture'])->name('get_all_facture');
Route::get('/delete_facture_user_id', [AjaxController::class , 'delete_facture_user_id'])->name('delete_facture_user_id');
Route::get('/get_all_categorie', [AjaxController::class , 'get_all_categorie'])->name('get_all_categorie');
Route::get('/get_all_stock', [AjaxController::class , 'get_all_stock'])->name('get_all_stock');
Route::get('/get_all_table', [AjaxController::class , 'get_all_table'])->name('get_all_table');
Route::get('/get_all_depense', [AjaxController::class , 'get_all_depense'])->name('get_all_depense');
Route::get('/get_all_articles', [AjaxController::class , 'get_all_articles'])->name('get_all_articles');
Route::get('/get_commune_by_district', [AjaxController::class , 'get_commune_by_district'])->name('get_commune_by_district');
Route::post('/save_paie_facture', [AjaxController::class , 'save_paie_facture'])->name('save_paie_facture');
Route::post('/delete_facture', [AjaxController::class , 'delete_facture'])->name('delete_facture');
Route::post('/process_payment', [AjaxController::class , 'process_payment'])->name('process_payment');
Route::post('/transfer_article', [AjaxController::class , 'transfer_article'])->name('transfer_article');
Route::post('/submit-filters', [AjaxController::class, 'submitFilters'])->name('submitFilters');
Route::post('/import_excel_categorie', [AjaxController::class, 'import_excel_categorie'])->name('import_excel_categorie');
Route::post('/import_excel_article', [AjaxController::class, 'import_excel_article'])->name('import_excel_article');
Route::post('/import_excel_depense', [AjaxController::class, 'import_excel_depense'])->name('import_excel_depense');
Route::get('/export_excel_categorie', [AjaxController::class , 'export_excel_categorie'])->name('export_excel_categorie');
Route::get('/export_excel_article', [AjaxController::class , 'export_excel_article'])->name('export_excel_article');
Route::get('/export_excel_depense', [AjaxController::class , 'export_excel_depense'])->name('export_excel_depense');
Route::get('/export_categories_pdf', [AjaxController::class , 'export_categories_pdf'])->name('export_categories_pdf');
Route::get('/export_article_pdf', [AjaxController::class , 'export_article_pdf'])->name('export_article_pdf');
Route::get('/export_depense_pdf', [AjaxController::class , 'export_depense_pdf'])->name('export_depense_pdf');
Route::post('/update_user_prestation', [AjaxController::class, 'update_user_prestation'])->name('update_user_prestation');
Route::post('/update_ronde', [AjaxController::class, 'update_ronde'])->name('update_ronde');
Route::get('/liberer_table', [AjaxController::class, 'liberer_table'])->name('liberer_table');
Route::get('/get_tables_select', [AjaxController::class, 'get_tables_select'])->name('get_tables_select');
Route::get('/get_articles_select', [AjaxController::class, 'get_articles_select'])->name('get_articles_select');
Route::get('/nettoyer_table', [AjaxController::class, 'nettoyer_table'])->name('nettoyer_table');
Route::get('/get_all_table_d', [AjaxController::class, 'get_all_table_d'])->name('get_all_table_d');
Route::get('/get_all_detail_achat_paie', [AjaxController::class, 'get_all_detail_achat_paie'])->name('get_all_detail_achat_paie');


// Route::get('/', function () {
//     $user = new User();
//     $user->name = "MGM GONGO";
//     $user->email = "jonathankaja675@gmail.com";
//     $user->password = Hash::make("12345");
//     $user->mdp = "12345";
//     $user->phone = "0974743675";
//     $user->role = 0;
//     $user->etat = 1;
//     $user->recherche = "";
//     $user->image = 'storage/images/user/profil_defaut.png';
//     $user->save();
// });

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('index');
Route::get('/utilisateurs', [App\Http\Controllers\HomeController::class, 'utilisateurs'])->name('utilisateurs');
Route::get('/postes', [App\Http\Controllers\HomeController::class, 'postes'])->name('postes');
Route::get('/droits', [App\Http\Controllers\HomeController::class, 'droits'])->name('droits');
Route::get('/invitations', [App\Http\Controllers\HomeController::class, 'invitations'])->name('invitations');
Route::get('/projets', [App\Http\Controllers\HomeController::class, 'projets'])->name('projets');
Route::get('/dossier_contentieux', [App\Http\Controllers\HomeController::class, 'dossier_contentieux'])->name('dossier_contentieux');
Route::get('/contrevenants', [App\Http\Controllers\HomeController::class, 'contrevenants'])->name('contrevenants');
Route::get('/verbalisateurs', [App\Http\Controllers\HomeController::class, 'verbalisateurs'])->name('verbalisateurs');
Route::get('/type_frais', [App\Http\Controllers\HomeController::class, 'type_frais'])->name('type_frais');
Route::get('/type_documents', [App\Http\Controllers\HomeController::class, 'type_documents'])->name('type_documents');
Route::get('/type_infractions', [App\Http\Controllers\HomeController::class, 'type_infractions'])->name('type_infractions');
Route::get('/decisions', [App\Http\Controllers\HomeController::class, 'decisions'])->name('decisions');
Route::get('/rapports', [App\Http\Controllers\HomeController::class, 'rapports'])->name('rapports');
Route::get('/gestion_societe', [App\Http\Controllers\HomeController::class, 'gestion_societe'])->name('gestion_societe');
Route::get('/gestion_solde', [App\Http\Controllers\HomeController::class, 'gestion_solde'])->name('gestion_solde');
Route::get('/gestion_article', [App\Http\Controllers\HomeController::class, 'gestion_article'])->name('gestion_article');
Route::get('/gestion_depense', [App\Http\Controllers\HomeController::class, 'gestion_depense'])->name('gestion_depense');
Route::get('/gestion_ecole', [App\Http\Controllers\HomeController::class, 'gestion_ecole'])->name('gestion_ecole');
Route::get('/gestion_beneficiaire', [App\Http\Controllers\HomeController::class, 'gestion_beneficiaire'])->name('gestion_beneficiaire');
Route::get('/rapport_pointage', [App\Http\Controllers\HomeController::class, 'rapport_pointage'])->name('rapport_pointage');
Route::get('/consulter_rapport', [App\Http\Controllers\HomeController::class, 'consulter_rapport'])->name('consulter_rapport');
Route::get('/entres', [App\Http\Controllers\HomeController::class, 'entres'])->name('entres');
Route::get('/sorties', [App\Http\Controllers\HomeController::class, 'sorties'])->name('sorties');
Route::get('/app_article', [App\Http\Controllers\HomeController::class, 'app_article'])->name('app_article');
Route::get('/achat_article', [App\Http\Controllers\HomeController::class, 'achat_article'])->name('achat_article');
Route::get('/bilan_sociale', [App\Http\Controllers\HomeController::class, 'bilan_sociale'])->name('bilan_sociale');
Route::get('/gestion_credit', [App\Http\Controllers\HomeController::class, 'gestion_credit'])->name('gestion_credit');
Route::get('/paie', [App\Http\Controllers\HomeController::class, 'paie'])->name('paie');
Route::get('/listesfactures', [App\Http\Controllers\HomeController::class, 'listesfactures'])->name('listesfactures');
Route::get('/alerte_centrale', [App\Http\Controllers\HomeController::class, 'alerte_centrale'])->name('alerte_centrale');
Route::get('/alerte_mobile', [App\Http\Controllers\HomeController::class, 'alerte_mobile'])->name('alerte_mobile');
Route::get('/gestion_fichier', [App\Http\Controllers\HomeController::class, 'gestion_fichier'])->name('gestion_fichier');
Route::get('/clients', [App\Http\Controllers\HomeController::class, 'clients'])->name('clients');
Route::get('/prospects', [App\Http\Controllers\HomeController::class, 'prospects'])->name('prospects');
Route::get('/profils', [App\Http\Controllers\HomeController::class, 'profils'])->name('profils');
Route::get('/gestion_activiter', [App\Http\Controllers\HomeController::class, 'gestion_activiter'])->name('gestion_activiter');
Route::get('/point_vente', [App\Http\Controllers\HomeController::class, 'point_vente'])->name('point_vente');
Route::get('/gestion_table', [App\Http\Controllers\HomeController::class, 'gestion_table'])->name('gestion_table');
Route::get('/gestion_stock', [App\Http\Controllers\HomeController::class, 'gestion_stock'])->name('gestion_stock');
Route::get('/rendez_vous', [App\Http\Controllers\HomeController::class, 'rendez_vous'])->name('rendez_vous');
Route::get('/scanner_rq_code', [App\Http\Controllers\OfficierController::class, 'scanner_rq_code'])->name('scanner_rq_code');
Route::get('/paiement', [App\Http\Controllers\PaiementController::class, 'paiement'])->name('paiement');
Route::get('/client_partager', [App\Http\Controllers\ClientController::class, 'client_partager'])->name('client_partager');
Route::get('/menu', [App\Http\Controllers\SiteController::class, 'menu'])->name('menu');
Route::get('/serveur_se', [App\Http\Controllers\HomeController::class, 'serveur_se'])->name('serveur_se');
Route::get('/debarrasseur_se', [App\Http\Controllers\HomeController::class, 'debarrasseur_se'])->name('debarrasseur_se');
